name: Local integration tests - Basic Version

on:
  # pull_request:
  #   branches: [main]
  push:

jobs:
  basic-integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-latest, windows-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [14, 16, 18]
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache dependencies
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies if no cache found
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Allow installing cert in Mac OS Big Sur
        run: sudo security authorizationdb write com.apple.trust-settings.admin allow
        if: matrix.os == 'macOS-latest'

      - name: Install mkcert
        run: brew install mkcert
        if: runner.os == 'MacOS'

      - name: Run mkcert setup [mkcert -install]
        run: mkcert -install
        if: runner.os == 'MacOS'

      - name: Install https cert [npm setup:https]
        run: npm run setup:https
        if: runner.os == 'MacOS'

      - run: |
          mkdir certs
          .\test\generate-cert.ps1
        shell: pwsh
        if: runner.os == 'Windows'

      - name: Run integration tests
        run: npm run test:integration
        shell: bash
